### ISSUE TITLE
How to disable using two GPUs for training?

### ISSUE THREAD

**Issue by davidvct** [JingyunLiang/SwinIR#134]
I have two GPUs on the computer. I am training SwinIR for denoising, it ran on two GPUs, even though I specified one or no GPU in the json file. I also tried setting the 'dist' to false, but it still ran on both GPUs.

I tried to specified which GPU to use in main_train_psnr.py as well, but got the same result:
```
def main():
    print("----project SwinIR------")

    os.environ["CUDA_DEVICES_ORDER"] = "PCI_BUS_ID"
    os.environ["CUDA_VISIBLE_DEVICES"] = '1'
```
I want to use only 1 GPU, if I can specified which GPU that would be nice.

Thanks.

**Comment by SaadAhmad376** [comment]
Try changing the gpu_ids list in whatever options file you are using

**Comment by IceyWuu** [comment]
> Try changing the gpu_ids list in whatever options file you are using

No it doesn't work, still got this problem

**Comment by IceyWuu** [comment]
I solved it by setting "gpu_ids=[0]" in options file and run with "--nproc_per_node=1", or python main_train_psnr.py --opt options/swinir/train_swinir_sr_classical.json

**Comment by clodiamery** [comment]
@IceyWuu , Please I need to know what is the resources that I need to run the code on my computer?

**Comment by clodiamery** [comment]
@davidvct , please when I run the code by using this : 
` python  main_train_psnr.py --opt options/swinir/train_swinir_sr_classical.json
`
I got on this error: 

```
 python  main_train_psnr.py --opt options/swinir/train_swinir_sr_classical.json
Terminal Width: 80
----project SwinIR------
----project SwinIR------
export CUDA_VISIBLE_DEVICES=0
number of GPUs is: 1
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose "Don't visualize my results"
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.4
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
LogHandlers setup!
25-01-18 07:10:47.793 :   task: swinir_sr_classical_patch48_x2
  model: plain
  gpu_ids: [0]
  dist: False
  scale: 2
  n_channels: 3
  path:[
    root: superresolution
    pretrained_netG: None
    pretrained_netE: None
    task: superresolution\swinir_sr_classical_patch48_x2
    log: superresolution\swinir_sr_classical_patch48_x2
    options: superresolution\swinir_sr_classical_patch48_x2\options
    models: superresolution\swinir_sr_classical_patch48_x2\models
    images: superresolution\swinir_sr_classical_patch48_x2\images
    pretrained_optimizerG: None
  ]
  datasets:[
    train:[
      name: train_dataset
      dataset_type: sr
      dataroot_H: trainsets/hr
      dataroot_L: trainsets/lr
      H_size: 96
      dataloader_shuffle: True
      dataloader_num_workers: 16
      dataloader_batch_size: 16
      phase: train
      scale: 2
      n_channels: 3
    ]
    test:[
      name: test_dataset
      dataset_type: sr
      dataroot_H: trainsets/lr
      dataroot_L: trainsets/lr
      phase: test
      scale: 2
      n_channels: 3
    ]
  ]
  netG:[
    net_type: swinir
    upscale: 2
    in_chans: 3
    img_size: 48
    window_size: 8
    img_range: 1.0
    depths: [6, 6, 6, 6, 6, 6]
    embed_dim: 180
    num_heads: [6, 6, 6, 6, 6, 6]
    mlp_ratio: 2
    upsampler: pixelshuffle
    resi_connection: 1conv
    init_type: default
    scale: 2
  ]
  train:[
    G_lossfn_type: l1
    G_lossfn_weight: 1.0
    E_decay: 0.999
    G_optimizer_type: adam
    G_optimizer_lr: 0.0001
    G_optimizer_wd: 0
    G_optimizer_clipgrad: None
    G_optimizer_reuse: True
    G_scheduler_type: MultiStepLR
    G_scheduler_milestones: [250000, 400000, 450000, 475000, 500000]
    G_scheduler_gamma: 0.5
    G_regularizer_orthstep: None
    G_regularizer_clipstep: None
    G_param_strict: True
    E_param_strict: True
    checkpoint_test: 5000
    checkpoint_save: 5000
    checkpoint_print: 200
    F_feature_layer: 34
    F_weights: 1.0
    F_lossfn_type: l1
    F_use_input_norm: True
    F_use_range_norm: False
  ]
  opt_path: options/swinir/train_swinir_sr_classical.json
  is_train: True
  merge_bn: False
  merge_bn_startpoint: -1
  find_unused_parameters: True
  num_gpu: 1
  rank: 0
  world_size: 1

Random seed: 1432
Dataset [DatasetSR - train_dataset] is created.
25-01-18 07:10:47.806 : Number of train images: 800, iters: 50
Dataset [DatasetSR - test_dataset] is created.
C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3588.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Pass this initialization! Initialization was done during network defination!
Pass this initialization! Initialization was done during network defination!
Training model [ModelPlain] is created.
Copying model for E ...
C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\optim\lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
Start the main training
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Terminal Width: 80
Traceback (most recent call last):
  File "C:\Users\pc\Desktop\1993\SwinIR-main\main_train_psnr.py", line 288, in <module>
    main()
  File "C:\Users\pc\Desktop\1993\SwinIR-main\main_train_psnr.py", line 214, in main
    for i, train_data in enumerate(train_loader):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\_utils.py", line 705, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "C:\Users\pc\Desktop\1993\SwinIR-main\data\dataset_sr.py", line 103, in __getitem__
    img_H, img_L = util.single2tensor3(img_H), util.single2tensor3(img_L)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\Desktop\1993\SwinIR-main\utils\utils_image.py", line 303, in single2tensor3
    return torch.from_numpy(np.ascontiguousarray(img)).permute(2, 0, 1).float()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().)

wandb:
wandb: You can sync this run to the cloud by running:
wandb: wandb sync C:\Users\pc\Desktop\1993\SwinIR-main\wandb\offline-run-20250118_071045-eya01rno
wandb: Find logs at: wandb\offline-run-20250118_071045-eya01rno\logs

```

Can you help me please
